# Generated by Django 2.2 on 2019-05-08 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressureTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_time', models.IntegerField(default=200, verbose_name='压测时长')),
                ('pre_num', models.IntegerField(default=100, verbose_name='并发数')),
                ('pre_type', models.IntegerField(choices=[(1, 'http'), (2, 'dubbo'), (3, 'websocket')], default=1, verbose_name='压测接口类型')),
                ('pre_interface_name', models.CharField(max_length=20, verbose_name='压测接口名称')),
                ('pre_interface', models.CharField(max_length=100, verbose_name='压测接口')),
                ('pre_interface_method', models.CharField(max_length=50, verbose_name='压测接口方法')),
                ('pre_interface_param_type', models.CharField(max_length=100, verbose_name='压测接口参数类型')),
                ('pre_interface_param_key', models.CharField(max_length=100, verbose_name='压测接口参数key')),
                ('pre_interface_param_value', models.CharField(max_length=100, verbose_name='压测接口参数value')),
            ],
            options={
                'verbose_name': '模块',
                'db_table': 'entity_pressure_test',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=30, verbose_name='模块名称')),
                ('module_type', models.IntegerField(choices=[(1, '教师空间'), (2, '教师pad'), (3, '学生pad'), (4, '商城')], default=1, verbose_name='模块类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('module_desc', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='模块描述')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.User')),
            ],
            options={
                'verbose_name': '模块',
                'db_table': 'entity_module',
            },
        ),
    ]
