# Generated by Django 2.2 on 2019-05-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20190508_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_env',
            field=models.IntegerField(choices=[(1, 'dev'), (2, 'docker-dev'), (3, 'docker-hotfix'), (4, 'stress')], default=1, verbose_name='项目环境'),
        ),
    ]
