# Generated by Django 2.2 on 2019-05-10 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_module_module_env'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressuretest',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='module', to='business.Module'),
        ),
    ]
