# Generated by Django 2.2 on 2019-05-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20190513_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressuretest',
            name='header',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='压测接口header'),
        ),
    ]
