# Generated by Django 2.2 on 2019-05-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_pressuretest_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressuretest',
            name='response_assert',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='响应断言'),
        ),
    ]
