# Generated by Django 2.2 on 2019-04-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=30, verbose_name='模块名称')),
                ('module_type', models.IntegerField(choices=[(1, '教师空间'), (2, '教师pad'), (3, '学生pad'), (4, '商城')], default=1, verbose_name='模块类型')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('module_desc', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='模块描述')),
            ],
            options={
                'verbose_name': '模块',
                'db_table': 'module',
            },
        ),
    ]
